
framwork:
    locale: en
    name: AJ-1.0
    dev: true
    
default:
    controller : home
    action : index
    404 :
        controller : home
        action : index
    500 :
        controller : home
        action : index

templating:
    engines: twig
    view_path : src/view
    public : src/view/public

database:
    dbname: 'AJ'
    user: 'root'
    password: 'sdfpro'
    host: '127.0.0.1'
    driver: 'pdo_mysql'
    charset: 'utf8'
    driverOptions:
        1002: 'SET NAMES utf8'

run:
    server : 0.0.0.0
    port : 8080

auth:
    cookie:
        name : authaj
        secure : false
        domain : localhost
        expire : 3600
        path : /
        httponly : true

    acl:
        db : user
        additional :
            adress : 
                type : string
                tail : 200
                nullable : false
                index : false
            age : 
                type : int
                tail : 3
                nullable : false
                index : false
                
        roles : admin ; superadmin ; sample


    